# Generated by Django 5.2 on 2025-04-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
                ('body', models.TextField()),
                ('blog_type', models.CharField(choices=[('food', 'Food'), ('travel', 'Travel'), ('lifestyle', 'Lifestyle'), ('technology', 'Technology'), ('fashion', 'Fashion'), ('fitness', 'Fitness'), ('health', 'Health'), ('education', 'Education'), ('business', 'Business'), ('entertainment', 'Entertainment')], max_length=50)),
                ('image', models.ImageField(upload_to='blogs_media/')),
            ],
        ),
    ]
