# Generated by Django 5.2 on 2025-05-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_blogs', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
